### ISSUE TITLE
migrations fix

### ISSUE THREAD

**Issue by gravityblast** [AsafSilman/idle-smart-treasury#13]
a couple of small fixes:

https://github.com/AsafSilman/idle-smart-treasury/blob/7cb28e9bc7bdae444e77abfa6ec0fd9bf2c898f4/migrations/8_configure_feecollector.js#L24

and

https://github.com/AsafSilman/idle-smart-treasury/blob/7cb28e9bc7bdae444e77abfa6ec0fd9bf2c898f4/migrations/20_integration_test.js#L95

should become `smartTreasuryBootstrapInstance.getCRPAddress`

**Comment by AsafSilman** [comment]
Migration fix added :)
