### ISSUE TITLE
contractState and feeBalances

### ISSUE THREAD

**Issue by gravityblast** [AsafSilman/idle-smart-treasury#14]
shall we set this public?

https://github.com/AsafSilman/idle-smart-treasury/blob/7cb28e9bc7bdae444e77abfa6ec0fd9bf2c898f4/contracts/SmartTreasuryBootstrap.sol#L38

we could change this

https://github.com/AsafSilman/idle-smart-treasury/blob/7cb28e9bc7bdae444e77abfa6ec0fd9bf2c898f4/contracts/FeeCollector.sol#L144

to 

`uint256[] memory feeBalances = new uint256[](allocations.length);`

just to be sure it's already initialized.

**Comment by AsafSilman** [comment]
Implemented contractState but, instead of making public I've made the state variable private and added a getter function.

No need to initialise feeBalances, since this will just cost extra gas. The array is initialised in `_amountsFromAllocations` before any access from this variable is required.
