### ISSUE TITLE
FeeCollector first review

### ISSUE THREAD

**Issue by bugduino** [AsafSilman/idle-smart-treasury#2]
Here are some other comments for the FeeCollector contract:

https://github.com/AsafSilman/idle-smart-treasury/blob/b39548b87275c6d7c6161cc26f21b5f281beae8e/contracts/FeeCollector.sol#L97 I think that this method, like the one in the SmartTreasuryBootstrap should accept a `bool[]` as a parameter in order to eventually skip the liquidation of some tokens to save on gas costs

Regarding those admin privileges in particular:
https://github.com/AsafSilman/idle-smart-treasury/blob/b39548b87275c6d7c6161cc26f21b5f281beae8e/contracts/FeeCollector.sol#L251

https://github.com/AsafSilman/idle-smart-treasury/blob/b39548b87275c6d7c6161cc26f21b5f281beae8e/contracts/FeeCollector.sol#L262

who's gonna be the admin? A multi-sig or the governance (Timelock.sol) itself? In case of the multi-sig maybe it should be somewhat restricted (eg do not allow to withdraw balancer pool shares or set some limits)

**Comment by AsafSilman** [comment]
re: deposit()
I will add this argument to deposit, this seems like a logical addition.

re admin:
governance will be the owner of the feeCollector, and thus the only address with rights to this.

I will slightly update the contract to include a third weight for the multisig. So governance can control the % of fees which are redirected to the smart treasury, fee treasury and multisig.

**Comment by bugduino** [comment]
Great!

**Comment by AsafSilman** [comment]
deposit boolean added f5e1a9d65ee4efa702a81020f56395f4b91cc03c

**Comment by bugduino** [comment]
https://github.com/AsafSilman/idle-smart-treasury/blob/b31be7c735eca92a3476751f20a5c52cb6a4f8e3/contracts/FeeCollector.sol#L124-L136 I think it's better to send directly WETH to beneficiaries at the end of the for loop because you will save a lot in terms of gas given that you are already doing the swap and you will save alle the token transfers. (We can potentially think of going a step further and introduce another buy back mechanism here by converting all the reserved fees for beneficiaries other than the smart treasury,  from WETH to IDLE in another tx potentially but that may need to be discussed further with the community)

https://github.com/AsafSilman/idle-smart-treasury/blob/b31be7c735eca92a3476751f20a5c52cb6a4f8e3/contracts/FeeCollector.sol#L214-L223
This may lead to misunderstanding I think, because you are first passing `_newAllocations[]` (probably looking at current allocations and current beneficiaries) but then inside the method the position of the last member is changed. Maybe we can simply support address(0) and skip it in the deposit() loop? Other ideas?

**Comment by AsafSilman** [comment]
re: deposit()
I agree with this,  I will add this change!

re: removeBeneficiaryAt()
I think it's better to keep this mechanism as is. If we introduce address(0)'s then we also have to account for the allocation that it is always set to zero, which is more overhead. The mechanism for how beneficiaries are removed should just be well understood by future governance so it is clear how the allocations work for this function. I can add a bit warning for this function, and example of how this mechanism works so its very clear.

**Comment by bugduino** [comment]
Sounds good to me

**Comment by AsafSilman** [comment]
I've implemented these changes as of 2d3763a3fe5adddf230fe9507f0924dad87ed53e
