### ISSUE TITLE
Tests rev 1

### ISSUE THREAD

**Issue by bugduino** [AsafSilman/idle-smart-treasury#6]
Hi @AsafSilman wanted to make some small comments regarding tests after a first revision (with @gravityblast):

For the SmartTreasuryBootstrap, even if it's used only once, could you add some more tests for the contract? For example about the ownership and privileges (the fact that only the owner can call specific methods) and about the state after the renounce and for the `withdraw` ?

For the FeeCollector:
I think you could also check the allocations of `allocation[1]` to be `100000` after this line https://github.com/AsafSilman/idle-smart-treasury/blob/main/test/test_feeCollector.js#L102 and in the same test a check for `depositTokens` could be made

Here https://github.com/AsafSilman/idle-smart-treasury/blob/957ec663ba1ea51096120cdab67428c765d764eb/test/test_feeCollector.js#L241 I think you should also check that you cannot set `beneficiary[0]`

For all other protected methods (with `onlyAdmin`) you should make a test or at least set an `expect` to check that no one other than the admin can call specific methods. I saw that you added this https://github.com/AsafSilman/idle-smart-treasury/blob/957ec663ba1ea51096120cdab67428c765d764eb/test/test_feeCollector.js#L208 but what needs to be tested is also that the modifier is present in critical methods

**Comment by AsafSilman** [comment]
I agree with all these test suggestions, added in d783d735a03cd718cb5cd08e792bff221a575561
