### ISSUE TITLE
Quick review (CRP-focused)

### ISSUE THREAD

**Issue by EndymionJkb** [AsafSilman/idle-smart-treasury#7]
This is just a cursory review - and focusing on the Smart Pool logic, vs the tokenomics or mechanics of the Treasury - but I do have some notes:

SmartTreasuryBootstrap:

swap() seems a little dangerous - you’re market buying whenever it’s called. Could check for a min balance (or at least 0) before trying to swap. Could pass in minAmounts in to guard against front-running/unexpected prices. Would be reassuring with large amounts.

_getCRPBoolAddress could check if there’s a crpAddress and revert with a message, vs calling on a possibly 0 address.

On the bootstrap contract, you’re supposed to call:
1) setIdlePerWeth (or initialize will revert)
2) swap
3) initialize
4) bootstrap

You’re checking in bootstrap that the smart pool exists (so you must have called initialize)
You’re indirectly checking that swap has been called in initialize (otherwise you probably wouldn’t have WETH balances) - but you need a require to ensure idlePerWeth has been set, or you will revert with division by zero. Maybe pass that into the constructor to eliminate one order dependency?

Initialize(): might want more than just non-zero balances. It has to be at least 10^-6 for Balancer to take it anyway - but you probably want some more substantial minimum. 

Example numbers: 

ETH = $1200
IDLE = $4.25

WETH = 5
IDLE = 10000; idleValueInWeth = 35.4167

idlePerWeth = 282.353
totalValueInPool = 40.4167

Math is weird and could be much simpler. To match what the smart pool GUI would do, 
the simplest math would be computing the percentages, then dividing by 4 for a total weight of 25.

For 5 WETH and 10,000 IDLE:

IDLE weight = idleValue / totalValue * 25 = 0.876288 * 25       ~ 21.9
WETH weight = wethValue / totalValue * 25 = 0.123711 * 25     ~ 3.1

The max total weight is 50 (98%/2%), but if you’re going to be changing weights, we recommend cutting the resolution to 96%/4% with a total of 25 (this avoids any possible boundary issues, and ensures pokeWeights will never fail).

So I would simply the math in this way, and also bounds check the final weights - you don’t want to waste gas trying to deploy a pool that won’t work. After calculating weights as above, and before trying to deploy a pool:

require(idleWeight >= 1 && idleWeight <= 24, ‘Invalid weights’);
-
CRP Rights - do you need all those rights? You need LP whitelisting and weight changes, but you’re not going to add/remove tokens, are you? So that at least should be false.

I’m fuzzy on what timelock is. It’s “governance,” but is it an EOA controlled by humans that will make calls on the CRP based on on-chain governance? That still requires total trust, so the rights should be minimized. You would only want it “wide open” like that if the controller is a contract that can only make calls based on on-chain voting or some other secure method - and maybe with some built-in limitations. What functions do you want the governance able to perform? Do you really want to be able to pause trading? Change the swap fee?

If the controller is a contract, you could have a two-step process: first "commit" a proposed change to smart pool parameters, with a timelock. Then people have to stake or call something on the contract over a certain threshold to approve the change - then anyone can call "apply()" - which would make the call on the contract if the timelock has expired and the vote/threshold was favorable. Then emit an event and clear the commit in either case.

You could also limit the contract in other ways. You're starting with a 0.5% swap fee, but if you can change it, maybe you limit it in the contract so that nobody can propose a fee > 2%. If the controller is an EOA, you could change the fee to anything at any time (within the 0.0001% to 10% protocol limit).

In bootstrap: Recommend setting end weights to 22.5/2.5 (total of 25 avoids poke issues - we have seen it fail specifically with 45/5). It is possible for pokeWeights to revert near the boundaries in some cases, and you really don’t want that happening here where it could get locked up (if timelock is an EOA you can make arbitrary calls with, it would always be fixable, but if it’s a contract, the calls are limited to what you wrote in that contract, so it could potentially get stuck if you need to call something and can’t.)

Glad to see somebody using removeWhitelistedLiquidityProvider! (Originally didn’t have that - added during the audit.)

—
FeeCollector is going to earn BAL tokens (assuming IDLE is eligible for mining earnings). Can you get them out after claiming? Looks like you can; admin can withdraw arbitrary tokens. Just keep that in mind - if you want to hold BPT tokens somewhere that can't withdraw BAL, you'll have to register a redirect.

The crp joinSwaps in FeeCollector are dangerous - ideally you’d want to compute (probably externally) and pass in minAmountOut so you don’t get rekt. Same with exit.

**Comment by AsafSilman** [comment]
Hi @EndymionJkb 

Thank you for your feedback and comments there's a lot here so I will go through each point
* I have taken onboard your recommendations regarding min token balances. 
* Implemented your suggestion for `_getCRPBoolAddress`
* Added check for `idlePerWeth` price in `initialize()`
* Simplified the weight math, and added suggested require code.
* Weights are now normalised to a total of 25. (Previously 50)
* Fix FeeCollector for joinSwaps and exitPool

Regarding CRP rights, we believe that the IDLE governance should have as much flexibility as possible for the pool, which is why we want to keep these rights available. including the possibility to change fee rates, add tokens, and even pause swapping if need be.

Regarding the 2 step process, the idle governance system is very similar to compound which already has a process similar to what you describe; in that, a proposal is proposed and voted upon, then send to a timelock contract if it passes. Perhaps @bugduino can provide any further insights if needed.

**Comment by EndymionJkb** [comment]
Thanks for the clarification on Timelock; makes sense then. 5 days should certainly be adequate. I thought you were most likely choosing them deliberately, but wanted to make sure (the hallmark of people just blindly turning them all on is when cap and LP are both true, which doesn't really make sense).

I suppose you might want to add/remove tokens if some flaw were discovered in the IDLE contract, and you had to replace it - or you wanted to switch to (or add) DAI as a reserve.

One other thing to consider is eventual migration to Balancer v2 (with many improvements in gas efficiency). You wouldn't have to migrate, of course, but it's worth considering how you would do it. Right now you can't replace the treasury beneficiary in the FeeCollector, but I suppose you could just add the new one and set the allocation to zero out the original treasury and send it to the new one. (Does it need some limitations on how the split can be allocated?)

The calls would all be different, so you might consider abstracting the deposit/withdrawUnderlying functions in a proxy with a defined interface. The v1 proxy would contain the crp address and implement that common deposit/withdrawal interface. When v2 comes out, you could write another implementation of the interface that contains the new pool and makes the corresponding v2 calls, and swap them out.

**Comment by AsafSilman** [comment]
Hey @EndymionJkb 

Thank you for this feedback, there is a function for the feeCollector to update the smart treasury through `setSmartTreasuryAddress`. Regarding future-proofing there are two approaches

1. Write a middleware contract to connect the feeCollector, and the new v2 pool.
2. Redeploy the feeCollector at a future date, and create a new governance proposal to direct fees there.

In any case we can move ahead with what is already created, and when v2 is up, we can re-evaluate the best choice for the IDLE protocol will be.
