### ISSUE TITLE
Use immutable keyword for state variables only set in constructor  

### ISSUE THREAD

**Issue by patitonar** [AsafSilman/idle-smart-treasury#8]
There are some state variables on the contracts that can be set as [immutable](https://docs.soliditylang.org/en/v0.6.5/contracts.html#immutable), this will save some gas when reading those variables in the other methods.

In `FeeCollector` the following state variable can be set as immutable:
- weth

In `SmartTreasuryBootstrap` the following variables can be set as immutable:
- timelock
- feeCollectorAddress
- balancer_bfactory
- balancer_crpfactory
- idle
- weth

On `FeeCollector` and `SmartTreasuryBootstrap`  given that the value is already known, the variable `uniswapRouterV2` can be set as constant, there is no need to initialize it in the constructor.

**Comment by AsafSilman** [comment]
HI pat,

Thank you for your feedback, I have added your recommendations in 5ce8ee8cd46aec5a8f1c5a8c1a726bc110c75f7f
